modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ModdingForBlockheads/TrashSlot/issues"

[[mods]]
modId="trashslot"
version="${file.jarVersion}"
displayName="TrashSlot"
displayURL="https://blay09.net/mods/trashslot"
logoFile="trashslot-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a trash slot to the inventory screen that allows deletion of unwanted items.
'''

[[dependencies.trashslot]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trashslot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trashslot]]
    modId="balm"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"
