modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/TrashSlot/issues"

[[mods]]
modId="trashslot"
version="${file.jarVersion}"
displayName="TrashSlot"
displayURL="https://blay09.net/mods/trashslot"
logoFile="trashslot-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Adds a trash slot to the inventory screen that allows deletion of unwanted items.
'''

[[dependencies.trashslot]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trashslot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trashslot]]
    modId="balm"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"
